### PR TITLE
adding mods

### PR DESCRIPTION
**Pull request by Minsekt**
led nozzle ducts, lgx lite umbilical mod, pcb mounting, native euclid mgn12h xcarriage, modified version of the warolf's sensorised hotend mount

### CODE REVIEW

**Comment by mandryd** [comment]
Nice work and thanks for the cool mods!  
Everything looks good, you just have a broken link on your "LGX_Lite_Umbilical" page (Sensorized Hotend-Carriage).

**Comment by Minsekt** [comment]
thanks! fixed it.

**Review by mandryd — COMMENTED** [review]
Hey I just realized, a lot of your urls and image urls that link within the repository are absolute links.  Can you swap those to relative?  Sorry, I didn't realize that the first time.  (I'm not usually on the receiving end of PRs).

**Comment by Minsekt** [comment]
fixed that too! 👍

**Comment by mandryd** [comment]
Thanks!

**Pull request merged**
